In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split

In [2]:
#Shuffling the data for better modelling
df= pd.read_excel('C:\\Users\\admin\\OneDrive\\Desktop\\ML A2\\Data_Cortex_Nuclear.xlsx')
df = df.sample(frac=1).reset_index(drop=True)
df

MouseID  DYRK1A_N   ITSN1_N    BDNF_N     NR1_N    NR2A_N    pAKT_N  \
0       3500_2  0.318166  0.528213  0.291024  2.421556  4.787251  0.205203   
1       363_14  0.590334  0.791139  0.331991  2.174914  3.023878  0.281646   
2       3422_8  0.293135  0.453547  0.308009  2.392220  3.738902  0.236384   
3       3520_5  0.630001  0.839187  0.357777  2.651229  4.261675  0.253184   
4       3415_5  0.542545  0.757917  0.350051  2.634509  4.735602  0.210526   
...        ...       ...       ...       ...       ...       ...       ...   
1075   3483_13  0.439808  0.604712  0.243761  1.793971  2.506688  0.178279   
1076   3416_10  0.418401  0.535349  0.279319  1.909812  2.686653  0.190453   
1077  J3295_13  0.228700  0.395179  0.234118  1.733184  2.220852  0.220665   
1078  50810A_1  0.488149  0.867264  0.438504  3.174743  4.158349  0.205755   
1079   3477_10  0.451309  0.647749  0.379476  2.057382  3.834764  0.294869   

       pBRAF_N  pCAMKII_N   pCREB_N  ...     BAD_N    BCL2_N     pS6_N  \
0     0.165672   6.253294  0.198446  ...  0.151275  0.137226  0.126640   
1     0.223533   4.934695  0.233314  ...  0.235017  0.166928  0.105899   
2     0.191533   3.610984  0.196568  ...  0.155342  0.144298  0.132053   
3     0.185257   3.816673  0.204940  ...  0.151166  0.107909  0.135334   
4     0.165671   3.871971  0.194297  ...  0.133358  0.112851  0.128635   
...        ...        ...       ...  ...       ...       ...       ...   
1075  0.145338   1.889599  0.176682  ...  0.161725  0.132225  0.089099   
1076  0.159564   1.791047  0.183019  ...       NaN  0.150644  0.109802   
1077  0.161435   1.989723  0.185164  ...  0.216682       NaN  0.118948   
1078  0.202858   2.522979  0.294838  ...  0.155004  0.147685  0.138609   
1079  0.207749   3.866806  0.222827  ...       NaN  0.119972  0.115017   

       pCFOS_N     SYP_N  H3AcK18_N    EGR1_N  H3MeK4_N    CaNA_N  Genotype  
0     0.136094  0.515281   0.185964  0.230441  0.188827  0.980758   Control  
1     0.141042  0.473800   0.207562  0.229840  0.278946  1.396454    Ts65Dn  
2     0.134814  0.368427   0.152941  0.209124  0.188956  0.928331   Control  
3     0.109897  0.496423   0.155008  0.153219       NaN  1.642886   Control  
4     0.142617  0.438354   0.110614  0.155667  0.146408  1.607631   Control  
...        ...       ...        ...       ...       ...       ...       ...  
1075  0.126984  0.329440   0.179096  0.193621  0.206499  1.114705    Ts65Dn  
1076  0.152843  0.400094   0.201854       NaN       NaN  1.698084    Ts65Dn  
1077  0.158296  0.422121   0.321306  0.229193  0.355213  1.430825    Ts65Dn  
1078  0.150069  0.759588   0.148312  0.165001  0.186750  2.077084   Control  
1079  0.103456  0.411348   0.201132  0.153238       NaN  1.392474   Control  

[1080 rows x 79 columns]

In [3]:
#Creating x and y
x = df.iloc[:, 1:-1]
y = df.iloc[:, -1].values
#Label encoding the last column of strings to integers
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, ..., 1, 0, 0])

In [4]:
#Filling in the missing values
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# Create an IterativeImputer object
imputer = IterativeImputer(random_state=0)

# Fit the imputer to your data
x = pd.DataFrame(imputer.fit_transform(x))
x

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\impute\_iterative.py:796: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(


0         1         2         3         4         5         6   \
0     0.318166  0.528213  0.291024  2.421556  4.787251  0.205203  0.165672   
1     0.590334  0.791139  0.331991  2.174914  3.023878  0.281646  0.223533   
2     0.293135  0.453547  0.308009  2.392220  3.738902  0.236384  0.191533   
3     0.630001  0.839187  0.357777  2.651229  4.261675  0.253184  0.185257   
4     0.542545  0.757917  0.350051  2.634509  4.735602  0.210526  0.165671   
...        ...       ...       ...       ...       ...       ...       ...   
1075  0.439808  0.604712  0.243761  1.793971  2.506688  0.178279  0.145338   
1076  0.418401  0.535349  0.279319  1.909812  2.686653  0.190453  0.159564   
1077  0.228700  0.395179  0.234118  1.733184  2.220852  0.220665  0.161435   
1078  0.488149  0.867264  0.438504  3.174743  4.158349  0.205755  0.202858   
1079  0.451309  0.647749  0.379476  2.057382  3.834764  0.294869  0.207749   

            7         8         9   ...        67        68        69  \
0     6.253294  0.198446  1.303075  ...  0.198881  0.151275  0.137226   
1     4.934695  0.233314  1.485328  ...  0.247254  0.235017  0.166928   
2     3.610984  0.196568  1.362929  ...  0.241777  0.155342  0.144298   
3     3.816673  0.204940  1.716583  ...  0.228736  0.151166  0.107909   
4     3.871971  0.194297  1.531613  ...  0.244469  0.133358  0.112851   
...        ...       ...       ...  ...       ...       ...       ...   
1075  1.889599  0.176682  1.187862  ...  0.217580  0.161725  0.132225   
1076  1.791047  0.183019  1.187314  ...  0.256362  0.182503  0.150644   
1077  1.989723  0.185164  0.884342  ...  0.290843  0.216682  0.170529   
1078  2.522979  0.294838  1.441072  ...  0.253377  0.155004  0.147685   
1079  3.866806  0.222827  1.624712  ...  0.228737  0.161787  0.119972   

            70        71        72        73        74        75        76  
0     0.126640  0.136094  0.515281  0.185964  0.230441  0.188827  0.980758  
1     0.105899  0.141042  0.473800  0.207562  0.229840  0.278946  1.396454  
2     0.132053  0.134814  0.368427  0.152941  0.209124  0.188956  0.928331  
3     0.135334  0.109897  0.496423  0.155008  0.153219  0.166831  1.642886  
4     0.128635  0.142617  0.438354  0.110614  0.155667  0.146408  1.607631  
...        ...       ...       ...       ...       ...       ...       ...  
1075  0.089099  0.126984  0.329440  0.179096  0.193621  0.206499  1.114705  
1076  0.109802  0.152843  0.400094  0.201854  0.193678  0.246999  1.698084  
1077  0.118948  0.158296  0.422121  0.321306  0.229193  0.355213  1.430825  
1078  0.138609  0.150069  0.759588  0.148312  0.165001  0.186750  2.077084  
1079  0.115017  0.103456  0.411348  0.201132  0.153238  0.190128  1.392474  

[1080 rows x 77 columns]

In [7]:
#Converting the values to the same scale
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x = pd.DataFrame(ss.fit_transform(x))
x

0         1         2         3         4         5         6   \
0    -0.433218 -0.354879 -0.569461  0.359701  1.014071 -0.674219 -0.599798   
1     0.660140  0.691702  0.261653 -0.351593 -0.877870  1.164057  1.543555   
2    -0.533775 -0.652086 -0.224872  0.275096 -0.110714  0.075622  0.358189   
3     0.819494  0.882956  0.784786  1.022053  0.450175  0.479619  0.125687   
4     0.468161  0.559462  0.628041  0.973835  0.958657 -0.546211 -0.599823   
...        ...       ...       ...       ...       ...       ...       ...   
1075  0.055445 -0.050375 -1.528294 -1.450196 -1.432768 -1.321689 -1.353011   
1076 -0.030553 -0.326475 -0.806910 -1.116122 -1.239681 -1.028942 -0.826053   
1077 -0.792627 -0.884419 -1.723928 -1.625500 -1.739444 -0.302393 -0.756743   
1078  0.249639  0.994716  2.422528  2.531818  0.339315 -0.660962  0.777678   
1079  0.101646  0.120935  1.225012 -0.690543 -0.007861  1.482056  0.958862   

            7         8         9   ...        67        68        69  \
0     2.101476 -0.435402 -0.269608  ... -0.959258 -0.316884 -0.030327   
1     1.081593  0.636281  0.121461  ...  0.710183  2.303552  0.952838   
2     0.057758 -0.493131 -0.141176  ...  0.521136 -0.189618  0.203748   
3     0.216850 -0.235796  0.617674  ...  0.071080 -0.320301 -1.000742   
4     0.259620 -0.562906  0.220776  ...  0.614062 -0.877534 -0.837166   
...        ...       ...       ...  ...       ...       ...       ...   
1075 -1.273663 -1.104315 -0.516824  ... -0.313932  0.010114 -0.195863   
1076 -1.349888 -0.909530 -0.518000  ...  1.024498  0.660291  0.413818   
1077 -1.196220 -0.843606 -1.168098  ...  2.214507  1.729804  1.072034   
1078 -0.783770  2.527223  0.026499  ...  0.921496 -0.200187  0.315870   
1079  0.255626  0.313964  0.420543  ...  0.071097  0.012061 -0.601467   

            70        71        72        73        74        75        76  
0     0.358712  0.232448  1.042262  0.124273  0.872094 -0.370180 -1.126338  
1    -1.094744  0.435347  0.417563  0.406144  0.858969  1.237827  0.185093  
2     0.738059  0.179940 -1.169338 -0.306718  0.406900 -0.367895 -1.291732  
3     0.967987 -0.841935  0.758265 -0.279744 -0.813036 -0.762671  0.962529  
4     0.498570  0.499968 -0.116241 -0.859134 -0.759615 -1.127082  0.851309  
...        ...       ...       ...       ...       ...       ...       ...  
1075 -2.272081 -0.141166 -1.756485  0.034626  0.068600 -0.054863 -0.703764  
1076 -0.821223  0.919335 -0.692437  0.331644  0.069857  0.667788  1.136666  
1077 -0.180275  1.142939 -0.360708  1.890623  0.844853  2.598689  0.293525  
1078  1.197494  0.805562  4.721519 -0.367129 -0.555947 -0.407254  2.332329  
1079 -0.455766 -1.106055 -0.522951  0.322232 -0.812626 -0.346971  0.172535  

[1080 rows x 77 columns]

In [8]:
#Creating train data and test data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2)

In [9]:
#Fitting the data into the SVM model
from sklearn.svm import SVC
classifier = SVC (kernel = 'rbf')
classifier.fit (x_train,y_train)

SVC()

In [10]:
#The predicted data for the test data
y_pred = classifier.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1])

In [17]:
#The predicted values by the model for the entire data
Y_pred= classifier.predict(x)
print (Y_pred)

#The predicted data for the entire model
df_ypred = pd.DataFrame(Y_pred,columns = ['Prediction'])
result = pd.DataFrame(pd.concat ([x,pd.DataFrame(y),df_ypred],axis = 1 ))
print(result)

[0 1 0 ... 1 0 0]
             0         1         2         3         4         5         6  \
0    -0.433218 -0.354879 -0.569461  0.359701  1.014071 -0.674219 -0.599798   
1     0.660140  0.691702  0.261653 -0.351593 -0.877870  1.164057  1.543555   
2    -0.533775 -0.652086 -0.224872  0.275096 -0.110714  0.075622  0.358189   
3     0.819494  0.882956  0.784786  1.022053  0.450175  0.479619  0.125687   
4     0.468161  0.559462  0.628041  0.973835  0.958657 -0.546211 -0.599823   
...        ...       ...       ...       ...       ...       ...       ...   
1075  0.055445 -0.050375 -1.528294 -1.450196 -1.432768 -1.321689 -1.353011   
1076 -0.030553 -0.326475 -0.806910 -1.116122 -1.239681 -1.028942 -0.826053   
1077 -0.792627 -0.884419 -1.723928 -1.625500 -1.739444 -0.302393 -0.756743   
1078  0.249639  0.994716  2.422528  2.531818  0.339315 -0.660962  0.777678   
1079  0.101646  0.120935  1.225012 -0.690543 -0.007861  1.482056  0.958862   

             7         8         9  ...      

In [18]:
#The accuracy score
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.9953703703703703


In [20]:
#The confusion matrix showing the correctly predicted and incorrectly predicted amount
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[108   1]
 [  0 107]]
